version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proboots-app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - proboots-network
    volumes:
      - ./src/db:/app/src/db
    deploy:
      resources:
        limits:
          memory: "1G"
        reservations:
          memory: "512M"

  apache:
    image: httpd:alpine
    container_name: proboots-apache
    depends_on:
      app:
        condition: service_started
        required: true
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - proboots-network
    volumes:
      - ./apache.conf:/usr/local/apache2/conf/httpd.conf
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      timeout: 10s
      interval: 30s
      retries: 3
    deploy:
      resources:
        limits:
          memory: "256M"
        reservations:
          memory: "128M"

networks:
  proboots-network:
    driver: bridge 